#!/bin/sh

item=$1
if [ -z "$2" ]
then
    options=''
else
    options=', "options": '"$2"
fi

case "$item" in
    [0-9])
	kodi-rpc Player.Open '{ "item": { "playlistid": '"$item"'}'"$options"' }'
	;;
    *)
	kodi-rpc Player.Open '{ "item": { "file": "'"$item"'"}'"$options"' }'
	;;
esac
